import {
  IsInt,
  IsNotEmpty,
  IsUUID,
  IsOptional,
  IsNumber,
  Min,
} from 'class-validator';

/**
 * DTO for manually creating a proposition.
 * Note: In normal flow, propositions are auto-generated by the system
 * via generateProposition(). This DTO exists for direct API usage.
 */
export class CreatePropositionCommandeDto {
  @IsInt()
  @IsNotEmpty()
  @Min(1, { message: 'Quantity must be at least 1' })
  quantiteProposee!: number;

  @IsUUID()
  @IsNotEmpty()
  produitId!: string;

  @IsUUID()
  @IsNotEmpty()
  fournisseurId!: string;

  @IsUUID()
  @IsNotEmpty()
  predictionId!: string;

  @IsNumber()
  @IsOptional()
  @Min(0)
  scoreFournisseur?: number;
}
