[pytest]
testpaths = tests
addopts =
    --alluredir=reports/allure-results
    --clean-alluredir
    --html=reports/report.html
    --self-contained-html
    -v
    --tb=short
log_cli = true
log_cli_level = INFO
markers =
    slow: mark test as slow
    smoke: mark test as smoke test
    regression: mark test as regression test
